services:
  postgres:
    container_name: Microservice-ticket
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TICKET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql